Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,15 +36,14 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
-
-    - name: Check Daemon JSON (Optional)
-      run: |
-       sudo cat /etc/docker/daemon.json || echo "daemon.json not found, using defaults"
-
+      
     - name: Set up Docker
       uses: docker-practice/actions-setup-docker@v1
       with:
         version: '20.10.7'
+    - name: Check Daemon JSON (Optional)
+      run: |
+       sudo cat /etc/docker/daemon.json || echo "daemon.json not found, using defaults"
 
     - name: Build Docker Image
       run: docker build -f Dockerfile -t myapp:latest .
